- hosts: 192.168.43.122
  tasks:
   - include_vars: "/root/Desktop/code/ansible/pass.txt"
   - command: "rpm -ivh /root/jdk-8u171-linux-x64.rpm"  
     register: injdk
     command_warnings: false
     ignore_errors: yes
     no_log: yes
   - debug:
      msg: "{{ injdk }}"
   
   - command: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm"  
     register: inhad
     ignore_errors: yes
     no_log: yes
   - debug:
      msg: "{{ inhad }}"


   - copy:
      dest: /etc/hadoop/hdfs-site.xml
      content: '<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>


<!-- Put site-specific property overrides in this file. -->


<configuration>

<property>

<name>dfs.data.dir</name>

<value>{{ dirhdfs }}</value>

</property>


</configuration>'
     register: fhdfs
   - debug:
      msg: "{{ fhdfs }}"

   - copy:
      dest: /etc/hadoop/mapred-site.xml
      content: '<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>


<!-- Put site-specific property overrides in this file. -->


<configuration>

<property>

<name>mapred.job.tracker</name>

<value>{{ taskip }}:9002</value>

</property>



</configuration>'
     register: fmap
   - debug:
      msg: "{{ fmap }}"

   - copy:
      dest: /etc/hadoop/core-site.xml
      content: '<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>


<!-- Put site-specific property overrides in this file. -->


<configuration>

<property>

<name>fs.default.name</name>

<value>hdfs://{{ masterip }}:9001</value>

</property>


</configuration>'
     register: fcore
   - debug:
      msg: "{{ fcore }}"
   - file:
      name: "{{ dirhdfs }}"
      state: directory
     register: dirnn
   - debug:
      msg: "{{ dirnn }}"    
   
   - service:
      name: firewalld
      state: stopped
   - command: "setenforce 0"
   - command: "hadoop-daemon.sh start datanode"
     register: startnn
   - debug:
      msg: "{{ startnn }}"
   - command: jps
     register: jps1
   - debug:
      msg: "{{ jps1 }}"
